layout_spectrum: 0.47022873345365984
typography_spectrum: 0.6530823365882003
color:
  brandStrength: 0.08957371969937836
  lightness: 0.8462100950554751
  saturation: 0.8707711508504973
  rhythmicContrast: 0.43679037901157935
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
coverPrefs:
  filter: false
github: true
author:
  name: Maria Gerace
  email: m.gerace@maricebyers.com
  url: mariageracebarrister.com
name: Maria Gerace Barrister
navigation:
  - name: Barrister Strategy Advice
    url: 'http://mariageracebarrister.com'
    type: external
title: Fraud Corruption Corporate Wrongs Whistleblower Protection
content: []
description: Strategy Advice Advocacy
