typography_spectrum: 0.15040250209777956
color:
  brandStrength: 0.5063987876297814
  lightness: 0.42186836610704953
  saturation: 0.8087845630385904
  rhythmicContrast: 0.5150321669031931
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
layout_spectrum: 0.221277461426683
author:
  name: Maria Gerace
  email: m.gerace@maricebyers.com
  url: mariageracebarrister.com
name: Maria Gerace Barrister
navigation:
  - name: Barrister Strategy Advice
    url: 'http://mariageracebarrister.com'
    type: external
title: Fraud Corruption Corporate Wrongs Whistleblower Protection
content: []
description: Representation Advice Strategy
